name: vocal_lens
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flexify: ^2.1.1
  flutter_screenutil: ^5.9.3
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  font_awesome_flutter: ^10.1.0
  google_generative_ai: ^0.4.6
  porcupine_flutter: ^3.0.4
  easy_localization: ^3.0.0
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/
